#include "pch.h"
/*
 * Map.c
 *
 * Utility functions for the map data structure.
 *
 */
#include <stdio.h>

#pragma warning (disable : 4201 4214 4115 4514)
#include <windows.h>
#pragma warning (default : 4201 4214 4115)

/* map line printf's */
#include <assert.h>
#include "Frame.h"
#include "FrameInt.h"
#define DEFINE_MAPINLINE	// defines the inline functions in this module
#include "Map.h"
#include "GTime.h"
#include "HCI.h"
#include "Projectile.h"
// chnaged line	- alex
#include "Display3D.h"
#include "Lighting.h"
// end of chnage - alex
#include "Game.h"
#include "Environ.h"
#include "AdvVis.h"
#include "Gateway.h"
#include "Wrappers.h"


BOOL bDoneWater = FALSE;
BOOL nearLand(UDWORD x, UDWORD y);
void mapWaterProcess(void);
MAPTILE* tileHasNeighbourType(UDWORD x, UDWORD y, TYPE_OF_TERRAIN type);

//scroll min and max values
SDWORD scrollMinX, scrollMaxX, scrollMinY, scrollMaxY;

/* Structure definitions for loading and saving map data */
using MAP_SAVEHEADER = struct _map_save_header
{
  STRING aFileType[4];
  UDWORD version;
  UDWORD width;
  UDWORD height;
};

#define SAVE_MAP_V2 \
	UWORD		texture; \
	UBYTE		height

using MAP_SAVETILEV2 = struct _map_save_tilev2
{
  SAVE_MAP_V2;
};

using MAP_SAVETILEV1 = struct _map_save_tilev1
{
  UDWORD texture;
  UBYTE type;
  UBYTE height;
};

using MAP_SAVETILE = struct _map_save_tile
{
  SAVE_MAP_V2;
};

using GATEWAY_SAVEHEADER = struct _gateway_save_header
{
  UDWORD version;
  UDWORD numGateways;
};

using GATEWAY_SAVE = struct _gateway_save
{
  UBYTE x0, y0, x1, y1;
};

using ZONEMAP_SAVEHEADER_V1 = struct _zonemap_save_header_v1
{
  UWORD version;
  UWORD numZones;
};

using ZONEMAP_SAVEHEADER = struct _zonemap_save_header
{
  UWORD version;
  UWORD numZones;
  UWORD numEquivZones;
  UWORD pad;
};

/* Floating point type for the aaLine */
// AAFLOAT's are interchangable with the FRACT type used in fractions.h
//
// - I couldn't bring myself to rewrite John's execellent fixed/floating point code
//
using AAFLOAT = float;

/* Sanity check definitions for the save struct file sizes */
#define SAVE_HEADER_SIZE	16
#define SAVE_TILE_SIZE		3
#define SAVE_TILE_SIZEV1	6
#define SAVE_TILE_SIZEV2	3

/* Floating point constants for aaLine */
/* Windows fpu version */
#define AA_ZERO				0.0F
#define AA_ONE				1.0F
#define AA_NINES			0.999
#define AA_HALF				0.5
#define AA_PMAX				1.0//\0.71			// Maximum perpendicular distance from line center

#define AADIV(a,b)			((AAFLOAT)(a)/(AAFLOAT)b)			// Floating point divide
#define AAMUL(a,b)			((AAFLOAT)(a)*(AAFLOAT)(b))			// Floating point multiply

/* Access the root table */
#define AARTFUNC(x) (aAARootTbl[ (UDWORD)((x) * ROOT_TABLE_SIZE) ])

// Maximun expected return value from get height
#define	MAX_HEIGHT			(256 * ELEVATION_SCALE)

/* Number of entries in the sqrt(1/(1+x*x)) table for aaLine */
#define	ROOT_TABLE_SIZE		1024

/* aaLine direction bits and tables */
#define DIR_STEEP			1  /* set when abs(dy) > abs(dx) */
#define DIR_NEGY			2  /* set whey dy < 0 */

/* Defines to access the map for aaLine */
#define PIXADDR(x,y)		mapTile(x,y)
#define PIXINC(dx,dy)		((dy * mapWidth) + dx)

/* The size and contents of the map */
UDWORD mapWidth = 0, mapHeight = 0;
MAPTILE* psMapTiles = nullptr;

/* The shift on the y coord when calculating into the map */

/* The map tiles generated by map calc line */
TILE_COORD* aMapLinePoints = nullptr;
static UDWORD maxLinePoints = 0;

/* The sqrt(1/(1+x*x)) table for aaLine */
AAFLOAT* aAARootTbl;

/* pixel increment values for aaLine                        */
/*   -- assume PIXINC(dx,dy) is a macro such that:          */
/*   PIXADDR(x0,y0) + PIXINC(dx,dy) = PIXADDR(x0+dx,y0+dy)  */
static int adj_pixinc[4];
static int diag_pixinc[4];
static int orth_pixinc[4];

/* Initialise the sqrt(1/(1+x*x)) lookup table */

/* Initialise the pixel offset tabels for aaLine */

/* Look up table that returns the terrain type of a given tile texture */
UBYTE terrainTypes[MAX_TILE_TEXTURES];

#define GETTILE_TEXTURE(tile) (tile->texture)

#define GETTILE_TEXTURE2(tile) (tile->texture)

/* pointer to a load map function - depends on version */
BOOL (*pLoadMapFunc)(UBYTE* pFileData, UDWORD fileSize);

MAPTILE* GetCurrentMap(void) // returns a pointer to the current loaded map data
{
  return (psMapTiles);
}

/* Create a new map of a specified size */
BOOL mapNew(UDWORD width, UDWORD height)
{
  UDWORD i; //, tmp, bitCount, widthShift;
  MAPTILE* psTile;

  /* See if a map has already been allocated */
  if (psMapTiles != nullptr)
  {
    /* Clear all the objects off the map and free up the map memory */
    freeAllDroids();
    freeAllStructs();
    freeAllFeatures();
    proj_FreeAllProjectiles();
    delete[] aMapLinePoints;
    aMapLinePoints = nullptr;
    psMapTiles = nullptr;
    aMapLinePoints = nullptr;
  }

  if (width * height > MAP_MAXAREA)
  {
    Neuron::Fatal("mapNew: map too large : {} {}\n",width,height);
    return FALSE;
  }

  //DON'T BOTHER ANYMORE
  /* Check the width is a power of 2 */
  /*bitCount = 0;
  tmp = width;
  widthShift = 0;
  for(i=0; i<32; i++)
  {
    if (tmp & 1)
    {
      bitCount ++;
      widthShift = i;
    }
    tmp = tmp >> 1;
  }
  if (bitCount != 1)
  {
    DBERROR(("mapNew: width must be a power of two"));
    return FALSE;
  }
  */

  psMapTiles = new (std::nothrow) MAPTILE[width*height];
  if (psMapTiles == nullptr)
  {
    Neuron::Fatal("mapNew: Out of memory");
    return FALSE;
  }
  memset(psMapTiles, 0, sizeof(MAPTILE) * width * height);

  mapWidth = width;
  mapHeight = height;

  for (i = 0; i < MAX_TILE_TEXTURES; i++)
    terrainTypes[i] = TER_SANDYBRUSH;

  /* Calculate the shift to use on y when indexing into the map array - USES mapWidth NOW*/

  /* Allocate a buffer for the LOS routines points */

  /* Initialise the root table for aaLine */

  intSetMapPos(mapWidth * TILE_UNITS / 2, mapHeight * TILE_UNITS / 2);

  /* Initialise the map terrain type */
  psTile = psMapTiles;
  environReset();
  /*set up the scroll mins and maxs - set values to valid ones for a new map*/
  scrollMinX = scrollMinY = 0;
  scrollMaxX = mapWidth;
  scrollMaxY = mapHeight;
  return TRUE;
}

/* load the map data - for version 1 */
BOOL mapLoadV1(UBYTE* pFileData, UDWORD fileSize)
{
  UDWORD i, j;
  MAP_SAVETILEV1* psTileData;

  /* Load in the map data */
  psTileData = (MAP_SAVETILEV1*)(pFileData + SAVE_HEADER_SIZE);
  for (i = 0; i < mapWidth * mapHeight; i++)
  {
    UDWORD DataTexture;

    DataTexture = GETTILE_TEXTURE(psTileData);
    // get the texture number
    psMapTiles[i].texture = static_cast<UWORD>(DataTexture & 0xffff);
    // get the flip bits
    psMapTiles[i].texture |= static_cast<UWORD>((DataTexture & 0xff000000) >> 16);
    psMapTiles[i].height = psTileData->height;
    // Changed line - alex
    //end of change - alex
    for (j = 0; j < MAX_PLAYERS; j++)
      psMapTiles[i].tileVisBits = static_cast<UBYTE>(((psMapTiles[i].tileVisBits) & ~static_cast<UBYTE>(1 << j)));
    psTileData = (MAP_SAVETILEV1*)(((UBYTE*)psTileData) + SAVE_TILE_SIZEV1);
  }
  if (((UBYTE*)psTileData) - pFileData > static_cast<SDWORD>(fileSize))
  {
    Neuron::Fatal("mapLoad: unexpected end of file");
    return FALSE;
  }

  if (!gwCreateNULLZoneMap())
    return FALSE;

  return TRUE;
}

/* load the map data - for version 1 */
BOOL mapLoadV2(UBYTE* pFileData, UDWORD fileSize)
{
  UDWORD i, j;
  MAP_SAVETILEV2* psTileData;

  /* Load in the map data */
  psTileData = (MAP_SAVETILEV2*)(pFileData + SAVE_HEADER_SIZE);
  for (i = 0; i < mapWidth * mapHeight; i++)
  {
    psMapTiles[i].texture = GETTILE_TEXTURE2(psTileData);

    psMapTiles[i].height = psTileData->height;
    // Changed line - alex
    //end of change - alex
    for (j = 0; j < MAX_PLAYERS; j++)
      psMapTiles[i].tileVisBits = static_cast<UBYTE>(((psMapTiles[i].tileVisBits) & ~static_cast<UBYTE>(1 << j)));
    psTileData = (MAP_SAVETILEV2*)(((UBYTE*)psTileData) + SAVE_TILE_SIZE);
  }

  if (((UBYTE*)psTileData) - pFileData > static_cast<SDWORD>(fileSize))
  {
    Neuron::Fatal("mapLoad: unexpected end of file");
    return FALSE;
  }

  if (!gwCreateNULLZoneMap())
    return FALSE;

  return TRUE;
}

/* load the map data - for version 3 */
BOOL mapLoadV3(UBYTE* pFileData, UDWORD fileSize)
{
  UDWORD i, j;
  MAP_SAVETILEV2* psTileData;
  GATEWAY_SAVEHEADER* psGateHeader;
  GATEWAY_SAVE* psGate;
  ZONEMAP_SAVEHEADER* psZoneHeader;
  UWORD ZoneSize;
  UBYTE* pZone;
  UBYTE* pDestZone;

  /* Load in the map data */
  psTileData = (MAP_SAVETILEV2*)(pFileData + SAVE_HEADER_SIZE);
  for (i = 0; i < mapWidth * mapHeight; i++)
  {
    psMapTiles[i].texture = GETTILE_TEXTURE2(psTileData);

    psMapTiles[i].height = psTileData->height;
    // Changed line - alex
    //end of change - alex
    for (j = 0; j < MAX_PLAYERS; j++)
      psMapTiles[i].tileVisBits = static_cast<UBYTE>(((psMapTiles[i].tileVisBits) & ~static_cast<UBYTE>(1 << j)));
    psTileData = (MAP_SAVETILEV2*)(((UBYTE*)psTileData) + SAVE_TILE_SIZE);
  }

  psGateHeader = (GATEWAY_SAVEHEADER*)psTileData;
  psGate = (GATEWAY_SAVE*)(psGateHeader + 1);

  DEBUG_ASSERT_TEXT(psGateHeader->version == 1, "Invalid gateway version");

  for (i = 0; i < psGateHeader->numGateways; i++)
  {
    if (!gwNewGateway(psGate->x0, psGate->y0, psGate->x1, psGate->y1))
    {
      Neuron::Fatal("mapLoadV3: Unable to add gateway");
      return FALSE;
    }
    psGate++;
  }

  //	if (!gwProcessMap())
  //
  //	if ((psGateways != NULL) &&
  //		!gwGenerateLinkGates())
  psZoneHeader = (ZONEMAP_SAVEHEADER*)psGate;

  DEBUG_ASSERT_TEXT((psZoneHeader->version == 1) || (psZoneHeader->version == 2), "Invalid zone map version");

  if (!gwNewZoneMap())
    return FALSE;

  // This is a bit nasty but should work fine.
  if (psZoneHeader->version == 1)
  {
    // version 1 so add the size of a version 1 header.
    pZone = ((UBYTE*)psZoneHeader) + sizeof(ZONEMAP_SAVEHEADER_V1);
  }
  else
  {
    // version 2 so add the size of a version 2 header.
    pZone = ((UBYTE*)psZoneHeader) + sizeof(ZONEMAP_SAVEHEADER);
  }

  for (i = 0; i < psZoneHeader->numZones; i++)
  {
    ZoneSize = *((UWORD*)(pZone));

    pDestZone = gwNewZoneLine(i, ZoneSize);

    if (pDestZone == nullptr)
      return FALSE;

    for (j = 0; j < ZoneSize; j++)
      pDestZone[j] = pZone[2 + j];

    pZone += ZoneSize + 2;
  }

  // Version 2 has the zone equivelancy lists tacked on the end.
  if (psZoneHeader->version == 2)
  {
    if (psZoneHeader->numEquivZones > 0)
    {
      // Load in the zone equivelance lists.
      if (!gwNewEquivTable(psZoneHeader->numEquivZones))
      {
        Neuron::Fatal("gwNewEquivTable failed");
        return FALSE;
      }

      for (i = 0; i < psZoneHeader->numEquivZones; i++)
      {
        if (*pZone != 0)
        {
          if (!gwSetZoneEquiv(i, *pZone, pZone + 1))
          {
            Neuron::Fatal("gwSetZoneEquiv failed");
            return FALSE;
          }
        }
        pZone += static_cast<UDWORD>(*pZone) + 1;
      }
    }
  }

  if (pZone - pFileData > static_cast<SDWORD>(fileSize))
  {
    Neuron::Fatal("mapLoadV3: unexpected end of file");
    return FALSE;
  }

  LOADBARCALLBACK(); //	loadingScreenCallback();

  if ((apEquivZones != nullptr) && !gwGenerateLinkGates())
    return FALSE;

  LOADBARCALLBACK(); //	loadingScreenCallback();

  //add new map initialise
  if (!gwLinkGateways())
    return FALSE;

  LOADBARCALLBACK(); //	loadingScreenCallback();

#if defined(DEBUG)
  gwCheckZoneSizes();
#endif

  return TRUE;
}

/* Initialise the map structure */
BOOL mapLoad(UBYTE* pFileData, UDWORD fileSize)
{
  UDWORD width, height;
  MAP_SAVEHEADER* psHeader;
  BOOL mapAlloc;

  /* Check the file type */
  psHeader = (MAP_SAVEHEADER*)pFileData;
  if (psHeader->aFileType[0] != 'm' || psHeader->aFileType[1] != 'a' || psHeader->aFileType[2] != 'p' || psHeader->aFileType[3] != ' ')
  {
    Neuron::Fatal("mapLoad: Incorrect file type");
    delete[] pFileData;
    pFileData = nullptr;
    return FALSE;
  }

  /* Check the file version - deal with version 1 files */
  /* Check the file version */
  if (psHeader->version < VERSION_7)
  {
    Neuron::Fatal("MapLoad: unsupported save format version {}",psHeader->version);
    delete[] pFileData;
    pFileData = nullptr;
    return FALSE;
  }
  if (psHeader->version <= VERSION_9)
    pLoadMapFunc = mapLoadV2;
  else if (psHeader->version <= CURRENT_VERSION_NUM)
    pLoadMapFunc = mapLoadV3; // Includes gateway data for routing.
  else
  {
    Neuron::Fatal("MapLoad: undefined save format version {}",psHeader->version);
    delete[] pFileData;
    pFileData = nullptr;
    return FALSE;
  }

  /* Get the width and height */
  width = psHeader->width;
  height = psHeader->height;

  if (width * height > MAP_MAXAREA)
  {
    Neuron::Fatal("mapLoad: map too large : {} {}\n",width,height);
    return FALSE;
  }

  //DON'T BOTHER ANYMORE
  /* Check the width is a power of 2 */
  /*bitCount = 0;
  tmp = width;
  widthShift = 0;
  for(i=0; i<32; i++)
  {
    if (tmp & 1)
    {
      bitCount ++;
      widthShift = i;
    }
    tmp = tmp >> 1;
  }
  if (bitCount != 1)
  {
    DBERROR(("mapLoad: width must be a power of two"));
    return FALSE;
  }
  */

  /* See if this is the first time a map has been loaded */
  mapAlloc = TRUE;
  if (psMapTiles != nullptr)
  {
    if (mapWidth == width && mapHeight == height)
      mapAlloc = FALSE;
    else
    {
      /* Clear all the objects off the map and free up the map memory */
      freeAllDroids();
      freeAllStructs();
      freeAllFeatures();
      proj_FreeAllProjectiles();
      delete[] aMapLinePoints;
      aMapLinePoints = nullptr;
      psMapTiles = nullptr;
      aMapLinePoints = nullptr;
    }
  }

  /* Allocate the memory for the map */
  if (mapAlloc)
  {
    psMapTiles = new (std::nothrow) MAPTILE[width*height];
    if (psMapTiles == nullptr)
    {
      Neuron::Fatal("mapLoad: Out of memory");
      return FALSE;
    }
    memset(psMapTiles, 0, sizeof(MAPTILE) * width * height);

    mapWidth = width;
    mapHeight = height;

    /*		a terrain type is loaded when necessary - so don't reset
        for (i=0; i<MAX_TILE_TEXTURES; i++)
        {
          terrainTypes[i] = TER_SANDYBRUSH;
        }*/
    /* Calculate the shift to use on y when indexing into the map array */

    /* Allocate a buffer for the LOS routines points */

    /* Initialise the root table for aaLine */
    //removed for NEW_SAVE //V11 Save
  }

  //load in the map data itself
  pLoadMapFunc(pFileData, fileSize);

  environReset();

  /* set up the scroll mins and maxs - set values to valid ones for any new map */
  scrollMinX = scrollMinY = 0;
  scrollMaxX = mapWidth;
  scrollMaxY = mapHeight;

  return TRUE;
}

/* Save the map data */
BOOL mapSave(UBYTE** ppFileData, UDWORD* pFileSize)
{
  UDWORD i;
  MAP_SAVEHEADER* psHeader;
  MAP_SAVETILE* psTileData;
  MAPTILE* psTile;
  GATEWAY* psCurrGate;
  GATEWAY_SAVEHEADER* psGateHeader;
  GATEWAY_SAVE* psGate;
  ZONEMAP_SAVEHEADER* psZoneHeader;
  UBYTE* psZone;
  UBYTE* psLastZone;
  SDWORD numGateways;

  // find the number of non water gateways
  numGateways = 0;
  for (psCurrGate = gwGetGateways(); psCurrGate; psCurrGate = psCurrGate->psNext)
  {
    if (!(psCurrGate->flags & GWR_WATERLINK))
      numGateways += 1;
  }

  /* Allocate the data buffer */
  *pFileSize = SAVE_HEADER_SIZE + mapWidth * mapHeight * SAVE_TILE_SIZE;
  // Add on the size of the gateway data.
  *pFileSize += sizeof(GATEWAY_SAVEHEADER) + sizeof(GATEWAY_SAVE) * numGateways;
  // Add on the size of the zone data header.
  *pFileSize += sizeof(ZONEMAP_SAVEHEADER);
  // Add on the size of the zone data.
  for (i = 0; i < gwNumZoneLines(); i++)
    *pFileSize += 2 + gwZoneLineSize(i);
  // Add on the size of the equivalency lists.
  for (i = 0; i < static_cast<UDWORD>(gwNumZones); i++)
    *pFileSize += 1 + aNumEquiv[i];

  *ppFileData = new (std::nothrow) UBYTE[*pFileSize];
  if (*ppFileData == nullptr)
  {
    Neuron::Fatal("Out of memory");
    return FALSE;
  }

  /* Put the file header on the file */
  psHeader = (MAP_SAVEHEADER*)*ppFileData;
  psHeader->aFileType[0] = 'm';
  psHeader->aFileType[1] = 'a';
  psHeader->aFileType[2] = 'p';
  psHeader->aFileType[3] = ' ';
  psHeader->version = CURRENT_VERSION_NUM;
  psHeader->width = mapWidth;
  psHeader->height = mapHeight;

  /* Put the map data into the buffer */
  psTileData = (MAP_SAVETILE*)(*ppFileData + SAVE_HEADER_SIZE);
  psTile = psMapTiles;
  for (i = 0; i < mapWidth * mapHeight; i++)
  {
    // don't save the noblock flag as it gets set again when the objects are loaded
    psTileData->texture = static_cast<UWORD>(psTile->texture & static_cast<UWORD>(~TILE_NOTBLOCKING));
    psTileData->height = psTile->height;

    psTileData = (MAP_SAVETILE*)((UBYTE*)psTileData + SAVE_TILE_SIZE);
    psTile++;
  }

  // Put the gateway header.
  psGateHeader = (GATEWAY_SAVEHEADER*)psTileData;
  psGateHeader->version = 1;
  psGateHeader->numGateways = numGateways;

  psGate = (GATEWAY_SAVE*)(psGateHeader + 1);

  i = 0;
  // Put the gateway data.
  for (psCurrGate = gwGetGateways(); psCurrGate; psCurrGate = psCurrGate->psNext)
  {
    if (!(psCurrGate->flags & GWR_WATERLINK))
    {
      psGate->x0 = psCurrGate->x1;
      psGate->y0 = psCurrGate->y1;
      psGate->x1 = psCurrGate->x2;
      psGate->y1 = psCurrGate->y2;
      psGate++;
      i++;
    }
  }

  // Put the zone header.
  psZoneHeader = (ZONEMAP_SAVEHEADER*)psGate;
  psZoneHeader->version = 2;
  psZoneHeader->numZones = static_cast<UWORD>(gwNumZoneLines());
  psZoneHeader->numEquivZones = static_cast<UWORD>(gwNumZones);

  // Put the zone data.
  psZone = (UBYTE*)(psZoneHeader + 1);
  for (i = 0; i < gwNumZoneLines(); i++)
  {
    psLastZone = psZone;
    *((UWORD*)psZone) = static_cast<UWORD>(gwZoneLineSize(i));
    psZone += sizeof(UWORD);
    memcpy(psZone, apRLEZones[i], gwZoneLineSize(i));
    psZone += gwZoneLineSize(i);
  }

  // Put the equivalency lists.
  if (gwNumZones > 0)
  {
    for (i = 0; i < static_cast<UDWORD>(gwNumZones); i++)
    {
      psLastZone = psZone;
      *psZone = aNumEquiv[i];
      psZone++;
      if (aNumEquiv[i])
      {
        memcpy(psZone, apEquivZones[i], aNumEquiv[i]);
        psZone += aNumEquiv[i];
      }
    }
  }

  DEBUG_ASSERT_TEXT(( ((UDWORD)psLastZone) - ((UDWORD)*ppFileData) ) < *pFileSize, "Buffer overflow saving map");

  return TRUE;
}

/* Shutdown the map module */
BOOL mapShutdown(void)
{
  if (psMapTiles) { delete[] psMapTiles; }
  psMapTiles = nullptr;
  mapWidth = mapHeight = 0;

  return TRUE;
}

/* work along a line on the map storing the points in aPoints.
 * The start and end points are in MAPTILE coordinates.
 */
void mapCalcLine(UDWORD startX, UDWORD startY, UDWORD endX, UDWORD endY, UDWORD* pNumPoints)
{
  UNUSEDPARAMETER(startX);
  UNUSEDPARAMETER(startY);
  UNUSEDPARAMETER(endX);
  UNUSEDPARAMETER(endY);
  UNUSEDPARAMETER(pNumPoints);
}

/* Initialise the sqrt(1/(1+x*x)) lookup table */
void mapRootTblInit(void) {}

/* Initialise the pixel offset tabels for aaLine */
void mapPixTblInit(void) {}

/* Fill in the aa line */
void mapCalcAALine(SDWORD X1, SDWORD Y1, SDWORD X2, SDWORD Y2, UDWORD* pNumPoints)
{
  UNUSEDPARAMETER(X1);
  UNUSEDPARAMETER(Y1);
  UNUSEDPARAMETER(X2);
  UNUSEDPARAMETER(Y2);
  UNUSEDPARAMETER(pNumPoints);
}

/* Return linear interpolated height of x,y */
extern SWORD map_Height(UDWORD x, UDWORD y)
{
  SDWORD retVal;
  UDWORD tileX, tileY, tileYOffset;
  SDWORD h0, hx, hy, hxy, wTL, wTR, wBL, wBR;
  SDWORD dx, dy, ox, oy;
  BOOL bWaterTile = FALSE;
  /*	ASSERT((x < (mapWidth << TILE_SHIFT),
      "mapHeight: x coordinate bigger than map width"));
    ASSERT((y < (mapHeight<< TILE_SHIFT),
      "mapHeight: y coordinate bigger than map height"));
  */
  x = x > SDWORD_MAX ? 0 : x; //negative SDWORD passed as UDWORD
  x = x >= (mapWidth << TILE_SHIFT) ? ((mapWidth - 1) << TILE_SHIFT) : x;
  y = y > SDWORD_MAX ? 0 : y; //negative SDWORD passed as UDWORD
  y = y >= (mapHeight << TILE_SHIFT) ? ((mapHeight - 1) << TILE_SHIFT) : y;

  /* Tile comp */
  tileX = x >> TILE_SHIFT;
  tileY = y >> TILE_SHIFT;

  /* Inter tile comp */
  ox = (x & (TILE_UNITS - 1));
  oy = (y & (TILE_UNITS - 1));

  if (TERRAIN_TYPE(mapTile(tileX,tileY)) == TER_WATER)
  {
    bWaterTile = TRUE;
    wTL = environGetValue(tileX, tileY) / 2;
    wTR = environGetValue(tileX + 1, tileY) / 2;
    wBL = environGetValue(tileX, tileY + 1) / 2;
    wBR = environGetValue(tileX + 1, tileY + 1) / 2;
  }

  tileYOffset = (tileY * mapWidth);

  DEBUG_ASSERT_TEXT(ox < TILE_UNITS, "mapHeight: x offset too big");
  DEBUG_ASSERT_TEXT(oy < TILE_UNITS, "mapHeight: y offset too big");
  DEBUG_ASSERT_TEXT(ox >= 0, "mapHeight: x offset too small");
  DEBUG_ASSERT_TEXT(oy >= 0, "mapHeight: y offset too small");

  //different code for 4 different triangle cases
  if (psMapTiles[tileX + tileYOffset].texture & TILE_TRIFLIP)
  {
    if ((ox + oy) > TILE_UNITS) //tile split top right to bottom left object if in bottom right half
    {
      ox = TILE_UNITS - ox;
      oy = TILE_UNITS - oy;
      hy = psMapTiles[tileX + tileYOffset + mapWidth].height;
      hx = psMapTiles[tileX + 1 + tileYOffset].height;
      hxy = psMapTiles[tileX + 1 + tileYOffset + mapWidth].height;
      if (bWaterTile)
      {
        hy += wBL;
        hx += wTR;
        hxy += wBR;
      }

      dx = ((hy - hxy) * ox) / TILE_UNITS;
      dy = ((hx - hxy) * oy) / TILE_UNITS;

      retVal = (hxy + dx + dy) * ELEVATION_SCALE;
      DEBUG_ASSERT_TEXT(retVal<MAX_HEIGHT, "Map height's gone weird!!!");
      return static_cast<SWORD>(retVal);
    }
    //tile split top right to bottom left object if in top left half
    h0 = psMapTiles[tileX + tileYOffset].height;
    hy = psMapTiles[tileX + tileYOffset + mapWidth].height;
    hx = psMapTiles[tileX + 1 + tileYOffset].height;

    if (bWaterTile)
    {
      h0 += wTL;
      hy += wBL;
      hx += wTR;
    }
    dx = ((hx - h0) * ox) / TILE_UNITS;
    dy = ((hy - h0) * oy) / TILE_UNITS;

    retVal = (h0 + dx + dy) * ELEVATION_SCALE;
    DEBUG_ASSERT_TEXT(retVal<MAX_HEIGHT, "Map height's gone weird!!!");
    return static_cast<SWORD>(retVal);
  }
  if (ox > oy) //tile split topleft to bottom right object if in top right half
  {
    h0 = psMapTiles[tileX + tileYOffset].height;
    hx = psMapTiles[tileX + 1 + tileYOffset].height;
    hxy = psMapTiles[tileX + 1 + tileYOffset + mapWidth].height;

    if (bWaterTile)
    {
      h0 += wTL;
      hx += wTR;
      hxy += wBR;
    }
    dx = ((hx - h0) * ox) / TILE_UNITS;
    dy = ((hxy - hx) * oy) / TILE_UNITS;
    retVal = (h0 + dx + dy) * ELEVATION_SCALE;
    DEBUG_ASSERT_TEXT(retVal<MAX_HEIGHT, "Map height's gone weird!!!");
    return static_cast<SWORD>(retVal);
  }
  //tile split topleft to bottom right object if in bottom left half
  h0 = psMapTiles[tileX + tileYOffset].height;
  hy = psMapTiles[tileX + tileYOffset + mapWidth].height;
  hxy = psMapTiles[tileX + 1 + tileYOffset + mapWidth].height;

  if (bWaterTile)
  {
    h0 += wTL;
    hy += wBL;
    hxy += wBR;
  }
  dx = ((hxy - hy) * ox) / TILE_UNITS;
  dy = ((hy - h0) * oy) / TILE_UNITS;

  retVal = (h0 + dx + dy) * ELEVATION_SCALE;
  DEBUG_ASSERT_TEXT(retVal<MAX_HEIGHT, "Map height's gone weird!!!");
  return static_cast<SWORD>(retVal);
  return 0;
}

/* returns TRUE if object is above ground */
extern BOOL mapObjIsAboveGround(BASE_OBJECT* psObj)
{
  SDWORD iZ, tileX = psObj->x >> TILE_SHIFT, tileY = psObj->y >> TILE_SHIFT, tileYOffset1 = (tileY * mapWidth), tileYOffset2 = ((tileY + 1)
           * mapWidth), h1 = psMapTiles[tileYOffset1 + tileX].height, h2 = psMapTiles[tileYOffset1 + tileX + 1].height, h3 = psMapTiles[
           tileYOffset2 + tileX].height, h4 = psMapTiles[tileYOffset2 + tileX + 1].height;

  /* trivial test above */
  if ((psObj->z > h1) && (psObj->z > h2) && (psObj->z > h3) && (psObj->z > h4))
    return TRUE;

  /* trivial test below */
  if ((psObj->z <= h1) && (psObj->z <= h2) && (psObj->z <= h3) && (psObj->z <= h4))
    return FALSE;

  /* exhaustive test */
  iZ = map_Height(psObj->x, psObj->y);
  if (psObj->z > iZ)
    return TRUE;
  return FALSE;
}

/* returns the max and min height of a tile by looking at the four corners 
   in tile coords */
void getTileMaxMin(UDWORD x, UDWORD y, UDWORD* pMax, UDWORD* pMin)
{
  UDWORD height, i, j;

  *pMin = TILE_MAX_HEIGHT;
  *pMax = TILE_MIN_HEIGHT;

  for (j = 0; j < 2; j++)
  {
    for (i = 0; i < 2; i++)
    {
      height = map_TileHeight(x + i, y + j);
      if (*pMin > height)
        *pMin = height;
      if (*pMax < height)
        *pMax = height;
    }
  }
}

UDWORD GetWidthOfMap(void) { return mapWidth; }

UDWORD GetHeightOfMap(void) { return mapHeight; }

// -----------------------------------------------------------------------------------
