#!/usr/bin/env python3
"""Compile every shipped .slo with the real script compiler.

crosscheck.py proves the compiler builds; this proves it accepts the game's
own scripts. The gap between those two is where `unknown type 'INT'` lived:
`int` and `bool` are lexer keywords rather than rows in asTypeTable, and
nothing in a C++ build can notice that the parser forgot it.

The compiler is NeuronCore/ScriptLex.cpp and NeuronCore/ScriptComp.cpp built
from source against the real NeuronCore headers, so this cannot drift from
what ships. Only two things are stood in for: the platform headers below the
script module (tools/scriptcorpus/pch.h and Frame.h), and the bodies of the
game entry points the symbol tables name -- see gen_tables() below.

The .vlo value files get a weaker check. Their parser is welded to live game
state -- droid ids, research names, sound tracks -- so it cannot run here;
instead every type name the corpus uses is checked against the game's own
asTypeTable plus the two keyword types. That catches data naming a type the
tables do not have, but not a parser that forgets one, so the .vlo dispatch
still needs its own reading.

Usage: python3 tools/check_scripts.py [--keep]
"""
import argparse
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
HARNESS = ROOT / 'tools' / 'scriptcorpus'

# Every callable in the symbol tables is a scr*/event*/interp* game entry
# point, and no constant is, so the prefix tells the two apart.
FUNC_PREFIX = re.compile(r'^(scr|event|interp)[A-Z]')

PREAMBLE = """\
/* Generated by tools/check_scripts.py -- do not edit, do not commit. */
#include "pch.h"
#include "Script.h"
#include "ScriptTabs.h"

/* Stands in for any game entry point, in either accessor shape. It has no
   integer conversion, so it can only satisfy the function-pointer fields,
   and it is never null -- the compiler ends the instinct table on a null
   pFunc, exactly as the game's "FUNCTION LIST END" row intends. */
static BOOL StubFunc(void) { return TRUE; }
static BOOL StubVarFunc(UDWORD) { return TRUE; }

struct StubFn
{
  constexpr operator SCRIPT_FUNC() const { return &StubFunc; }
  constexpr operator SCRIPT_VARFUNC() const { return &StubVarFunc; }
};

static constexpr StubFn kStubFn{};

/* The game identifiers the table initialisers name. Their values cannot
   affect whether a script compiles, so the constants are all zero. */
"""


def type_names():
    """The user type names, read from the game's own asTypeTable."""
    text = (ROOT / 'Outpost/ScriptTabs.cpp').read_text()
    start = text.index('TYPE_SYMBOL asTypeTable')
    return set(re.findall(r'"([A-Za-z_]\w*)"', text[start:text.index('};', start)]))


def gen_tables(out_dir):
    """Turn Outpost/ScriptTabs.cpp into a standalone Tables.cpp.

    The tables are pure static initialisers, so the only thing between them
    and a host compile is the game identifiers they name: instinct-function
    pointers, variable accessors, and the game enums used as constant
    values. Those get stubbed. Everything structural -- the ST_* type ids,
    the CALL_* callback ids, the VAL_* base types -- stays symbolic and
    comes from the real ScriptTabs.h.
    """
    tabs_h = (ROOT / 'Outpost/ScriptTabs.h').read_text()
    tabs_c = (ROOT / 'Outpost/ScriptTabs.cpp').read_text()

    lines = tabs_c.splitlines()
    start = next(i for i, l in enumerate(lines) if l.startswith('/* The table of user defined types'))
    end = next(i for i, l in enumerate(lines) if l.startswith('BOOL scrTabInitialise'))
    body = '\n'.join(lines[start:end]).rstrip()

    known = set(re.findall(r'^\s*(\w+)\s*(?:=|,|$)', tabs_h, re.M))
    known |= set(re.findall(r'#define\s+(\w+)', tabs_h))
    for header in ('Interp.h', 'Parse.h', 'Script.h', 'Stack.h', 'Event.h'):
        text = (ROOT / 'NeuronCore' / header).read_text()
        known |= set(re.findall(r'\b(?:VAL_|TR_|AT_|ST_|SCRIPT_|CR_)\w+\b', text))
        known |= set(re.findall(r'#define\s+(\w+)', text))
        known |= set(re.findall(r'using\s+(\w+)\s*=', text))
    known |= {'nullptr', 'NULL', 'TRUE', 'FALSE', 'true', 'false',
              'void', 'int', 'char', 'unsigned', 'const', 'static', 'extern',
              'sizeof', 'reinterpret_cast', 'static_cast'}
    known |= set(re.findall(r'^\w+\s+(\w+)\[\]\s*=', body, re.M))

    # comments and string literals are data, not identifiers
    code = re.sub(r'/\*.*?\*/', ' ', body, flags=re.S)
    code = re.sub(r'//[^\n]*', ' ', code)
    code = re.sub(r'"(?:[^"\\]|\\.)*"', ' ', code)
    undefined = sorted(set(re.findall(r'\b[A-Za-z_]\w*\b', code)) - known)

    stubs = '\n'.join(f'#define {u} kStubFn' if FUNC_PREFIX.match(u) else f'#define {u} 0'
                      for u in undefined)
    (out_dir / 'Tables.cpp').write_text(PREAMBLE + stubs + '\n\n' + body + '\n')
    return len(undefined)


def check_vlo(names):
    """Every type a value file names must be one the .vlo parser accepts.

    A binding is `variable [subscripts] TYPE value`; the type token is the
    identifier immediately before the value.
    """
    binding = re.compile(
        r'\b[A-Za-z_]\w*(?:\s*\[\s*\d+\s*\])*\s+([A-Za-z_]\w*)\s+'
        r'(?:-?\d+|"[^"]*"|\w+)\s*(?=[A-Za-z_"}])')
    accepted = names | {'int', 'INT', 'bool', 'BOOL'}
    bad = []
    files = sorted(ROOT.rglob('*.vlo'))
    for path in files:
        text = re.sub(r'/\*.*?\*/', ' ', path.read_text(errors='replace'), flags=re.S)
        text = re.sub(r'//[^\n]*', ' ', text)
        for match in binding.finditer(text):
            if match.group(1) not in accepted:
                bad.append(f'{path.relative_to(ROOT)}: unknown type {match.group(1)!r}')
    return files, bad


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--keep', action='store_true', help='keep the build directory')
    args = parser.parse_args()

    scripts = sorted(p for p in ROOT.rglob('*') if p.suffix.lower() == '.slo')
    if not scripts:
        print('no .slo files found', file=sys.stderr)
        return 1

    build = pathlib.Path(tempfile.mkdtemp(prefix='scriptcorpus-'))
    try:
        stubbed = gen_tables(build)
        # A quoted include always resolves against the including file's own
        # directory first, so the compiler sources have to sit beside the
        # stand-in pch.h rather than beside NeuronCore's. They are copied
        # fresh every run; their headers still come from NeuronCore.
        sources = [build / 'Tables.cpp', HARNESS / 'main.cpp']
        for name in ('ScriptLex.cpp', 'ScriptComp.cpp'):
            shutil.copy(ROOT / 'NeuronCore' / name, build / name)
            sources.append(build / name)

        binary = build / 'scriptcorpus'
        compile_cmd = [
            'g++', '-std=c++20', '-g', '-o', str(binary),
            '-I', str(HARNESS),
            '-I', str(ROOT / 'NeuronCore'), '-I', str(ROOT / 'Outpost'),
        ] + [str(p) for p in sources]
        result = subprocess.run(compile_cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(result.stdout + result.stderr, file=sys.stderr)
            print('FAILED to build the script corpus harness', file=sys.stderr)
            return 1
        print(f'harness built ({stubbed} game identifiers stubbed)')

        result = subprocess.run([str(binary)] + [str(p) for p in scripts],
                                capture_output=True, text=True)
        print(result.stdout + result.stderr, end='')
        slo_ok = result.returncode == 0
    finally:
        if args.keep:
            print(f'build directory kept at {build}')
        else:
            shutil.rmtree(build, ignore_errors=True)

    vlo_files, vlo_bad = check_vlo(type_names())
    for line in vlo_bad:
        print(line)
    print(f'checked {len(vlo_files)} value files, {len(vlo_bad)} bad types')

    if not slo_ok or vlo_bad:
        print('FAILED')
        return 1
    print('OK')
    return 0


if __name__ == '__main__':
    sys.exit(main())
